### PR TITLE
Update to 1.1.1

### PR DESCRIPTION
**Pull request by deepkrg17**
#### Imports
- imr : import React
- imrd : import ReactDom
- imrc : import React and React.Component
- impf : import own components
- imps : import useState or any other Hook
- impse : import useState and useEffect
- impt : import Prototypes
#### Skeletons
- rcc : React Class Component
- rfc : React Functional Component
- rfce : React Functional Component with export at end
- rafc : React Arrow Functional Component
#### Hooks
- uste : useState
- usef : useEffect
- rcontext : React.createContext
- ucontext : useContext

### JavaScript Snippets (new)
- prom : Promise

### CODE REVIEW

**Comment by deadlyjack** [comment]
Hi, thanks for the pull request but can you update es5 snippets to es6 like var to let/const, class to es6 class. Thanks for the help 😉

**Comment by deepkrg17** [comment]
Are you talking about the old snippets?
I don't think I have added any es5 snippet.

**Comment by deepkrg17** [comment]
Are you talking about the old snippets?
I don't think I have added any es5 snippet.

**Comment by deepkrg17** [comment]
# Update to 1.1.1

### Updated JavaScript snippets with ES6 syntax.

## New JS snippets
- class
- constructor
- method
- this. (eg. this.value = value)

**Comment by deepkrg17** [comment]
## Update to 1.1.1

#### Updated JavaScript snippets with ES6 syntax.

### New JS snippets
- class
- constructor
- method
- this. (eg. this.value = value)

**Pull request merged**
