### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by bajrangCoder**
Tried to fix issue....

### CODE REVIEW

**Comment by deepkrg17** [comment]
This will not solve the issue. Plugin has no action with file `package.json`.
This issue is for any other thing.

**Comment by bajrangCoder** [comment]
> This will not solve the issue. Plugin has no action with file `package.json`. This issue is for any other thing.

Ok, you have any idea how to test any plugin on Acode with github

**Comment by deepkrg17** [comment]
Maybe you mean "on GitHub with Acode".
It can be tested by adding it with "+" icon in Plugins section.
The link will be "https://raw.githubusercontent.com/<owner>/<repo>/<branch>/"

**Comment by deepkrg17** [comment]
Maybe you mean "on GitHub with Acode".
It can be added using the "+" icon in Plugins section.
The link will be `https://raw.githubusercontent.com/<owner>/<repo>/<branch>/`

**Pull request closed without merging**
